# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import travel_pb2 as travel__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in travel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TravelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRoute = channel.unary_unary(
                '/travel.TravelService/CreateRoute',
                request_serializer=travel__pb2.CreateRouteRequest.SerializeToString,
                response_deserializer=travel__pb2.CreateRouteResponse.FromString,
                _registered_method=True)
        self.GetRoute = channel.unary_unary(
                '/travel.TravelService/GetRoute',
                request_serializer=travel__pb2.GetRouteRequest.SerializeToString,
                response_deserializer=travel__pb2.RouteDto.FromString,
                _registered_method=True)
        self.StreamPlaceUpdates = channel.unary_stream(
                '/travel.TravelService/StreamPlaceUpdates',
                request_serializer=travel__pb2.StreamPlaceRequest.SerializeToString,
                response_deserializer=travel__pb2.PlaceUpdate.FromString,
                _registered_method=True)


class TravelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRoute(self, request, context):
        """Создание маршрута
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoute(self, request, context):
        """Получение информации о маршруте
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPlaceUpdates(self, request, context):
        """Серверный стриминг: обновления мест по маршруту
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TravelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRoute,
                    request_deserializer=travel__pb2.CreateRouteRequest.FromString,
                    response_serializer=travel__pb2.CreateRouteResponse.SerializeToString,
            ),
            'GetRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoute,
                    request_deserializer=travel__pb2.GetRouteRequest.FromString,
                    response_serializer=travel__pb2.RouteDto.SerializeToString,
            ),
            'StreamPlaceUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPlaceUpdates,
                    request_deserializer=travel__pb2.StreamPlaceRequest.FromString,
                    response_serializer=travel__pb2.PlaceUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'travel.TravelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('travel.TravelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TravelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel.TravelService/CreateRoute',
            travel__pb2.CreateRouteRequest.SerializeToString,
            travel__pb2.CreateRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/travel.TravelService/GetRoute',
            travel__pb2.GetRouteRequest.SerializeToString,
            travel__pb2.RouteDto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPlaceUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/travel.TravelService/StreamPlaceUpdates',
            travel__pb2.StreamPlaceRequest.SerializeToString,
            travel__pb2.PlaceUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
