# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: travel.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'travel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctravel.proto\x12\x06travel\"j\n\x12\x43reateRouteRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x12\n\nstart_date\x18\x03 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x04 \x01(\t\x12\x0e\n\x06\x62udget\x18\x05 \x01(\x02\"7\n\x13\x43reateRouteResponse\x12\x10\n\x08route_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"#\n\x0fGetRouteRequest\x12\x10\n\x08route_id\x18\x01 \x01(\t\"\x82\x01\n\x08RouteDto\x12\x10\n\x08route_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x12\n\nstart_date\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x05 \x01(\t\x12\x0e\n\x06\x62udget\x18\x06 \x01(\x02\x12\x0e\n\x06status\x18\x07 \x01(\t\"&\n\x12StreamPlaceRequest\x12\x10\n\x08route_id\x18\x01 \x01(\t\"h\n\x0bPlaceUpdate\x12\x10\n\x08route_id\x18\x01 \x01(\t\x12\x12\n\nplace_name\x18\x02 \x01(\t\x12\x12\n\nvisit_date\x18\x03 \x01(\t\x12\x0c\n\x04note\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t2\xd7\x01\n\rTravelService\x12\x46\n\x0b\x43reateRoute\x12\x1a.travel.CreateRouteRequest\x1a\x1b.travel.CreateRouteResponse\x12\x35\n\x08GetRoute\x12\x17.travel.GetRouteRequest\x1a\x10.travel.RouteDto\x12G\n\x12StreamPlaceUpdates\x12\x1a.travel.StreamPlaceRequest\x1a\x13.travel.PlaceUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'travel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEROUTEREQUEST']._serialized_start=24
  _globals['_CREATEROUTEREQUEST']._serialized_end=130
  _globals['_CREATEROUTERESPONSE']._serialized_start=132
  _globals['_CREATEROUTERESPONSE']._serialized_end=187
  _globals['_GETROUTEREQUEST']._serialized_start=189
  _globals['_GETROUTEREQUEST']._serialized_end=224
  _globals['_ROUTEDTO']._serialized_start=227
  _globals['_ROUTEDTO']._serialized_end=357
  _globals['_STREAMPLACEREQUEST']._serialized_start=359
  _globals['_STREAMPLACEREQUEST']._serialized_end=397
  _globals['_PLACEUPDATE']._serialized_start=399
  _globals['_PLACEUPDATE']._serialized_end=503
  _globals['_TRAVELSERVICE']._serialized_start=506
  _globals['_TRAVELSERVICE']._serialized_end=721
# @@protoc_insertion_point(module_scope)
